In [1]:
label_map = {
    "0":"0",
    "1":"6",
    "2":"4",
    "3":"2",
    "4":"8",
    "5":"10",
    "6":"0",
    "7":"8",
    "8":"27",
    "9":"16",
    "10":"6",
    "11":"4",
    "12":"2",
    "13":"10",
    "14":"14",
    "15":"12",
    "16":"20",
    "17":"36",
    "18":"35"
}

In [21]:
label_mapping = {
            0: [1, 0],
            1: [1, 0],
            2: [1, 1],
            3: [1, 1],
            4: [1, 2],
            5: [1, 2],
            6: [1, 3],
            7: [1, 3],
            8: [0, 0],
            9: [0, 0],
            10: [0, 1],
            11: [0, 1],
            12: [0, 2],
            13: [0, 2],
            14: [0, 3],
            15: [0, 3],
            16: [2, 0],
            17: [2, 0],
            18: [2, 1],
            19: [2, 1],
            20: [2, 2],
            21: [2, 2],
            22: [2, 3],
            23: [2, 3],
            24: [3, 9],
            25: [0, 9],
            26: [1, 9],
            27: [2, 9],
            28: [4, 9],
            29: [0, 5],
            30: [1, 5],
            31: [2, 5],
            32: [0, 9],
            33: [1, 9],
            34: [2, 9],
            35: [1, 8],
            36: [0, 8],
            37: [1, 8],
            38: [1, 8],
            39: [1, 4],
            40: [0, 4],
            41: [2, 4],
            42: [0, 6],
            43: [1, 6],
            44: [0, 7],
            45: [1, 7],
            46: [1, 9],
            47: [0, 9],
            48: [1, 9],
            49: [0, 9]
        }

a = torch.tensor(list(label_mapping.values()))
a

tensor([[1, 0],
        [1, 0],
        [1, 1],
        [1, 1],
        [1, 2],
        [1, 2],
        [1, 3],
        [1, 3],
        [0, 0],
        [0, 0],
        [0, 1],
        [0, 1],
        [0, 2],
        [0, 2],
        [0, 3],
        [0, 3],
        [2, 0],
        [2, 0],
        [2, 1],
        [2, 1],
        [2, 2],
        [2, 2],
        [2, 3],
        [2, 3],
        [3, 9],
        [0, 9],
        [1, 9],
        [2, 9],
        [4, 9],
        [0, 5],
        [1, 5],
        [2, 5],
        [0, 9],
        [1, 9],
        [2, 9],
        [1, 8],
        [0, 8],
        [1, 8],
        [1, 8],
        [1, 4],
        [0, 4],
        [2, 4],
        [0, 6],
        [1, 6],
        [0, 7],
        [1, 7],
        [1, 9],
        [0, 9],
        [1, 9],
        [0, 9]])

In [17]:
c = torch.arange((15)).reshape((1,3,5))
c

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]])

In [18]:
# c = torch.arange((1,3,5))
a[...,:5] = c
a

tensor([[[ 0.,  1.,  2.,  3.,  4.,  0.,  0.,  0.,  0.,  0.],
         [ 5.,  6.,  7.,  8.,  9.,  0.,  0.,  0.,  0.,  0.],
         [10., 11., 12., 13., 14.,  0.,  0.,  0.,  0.,  0.]]])

In [22]:
import torch

# 假设a是1*5*4*22的张量
a = torch.randn(1, 5, 4, 22)

# 假设b是22*21的张量
b = torch.randn(22, 21)

# 执行矩阵乘法，将最后一个维度(22)与第一个维度(22)进行矩阵乘法
result = torch.matmul(a, b)

# 结果的形状是1*5*4*21
print(result.shape)

torch.Size([1, 5, 4, 21])


In [25]:
import torch

# 假设你有一个形状为(1, 2, 2, 2, 3)的张量
original_tensor = torch.randint(0, 3, (1, 2, 2, 2, 1))  # 假设张量中的值是0, 1, 2

# 获取类别的数量
num_classes = original_tensor.max() + 1

# 使用torch.eye创建单位矩阵，维度为(3, 3)，其中3是类别的数量
eye_matrix = torch.eye(num_classes)

# 使用索引操作符将原始张量映射到对应的单位矩阵的行
one_hot_tensor = eye_matrix[original_tensor.squeeze()]

# 在第一个维度上添加一个维度，使得形状变为(1, 2, 2, 2, 3)
one_hot_tensor = one_hot_tensor.unsqueeze(0)

print(one_hot_tensor.shape)


torch.Size([1, 2, 2, 2, 3])


In [ ]:
torch.Tensor

In [74]:
label_mapping = {
            0: [1, 0],
            1: [1, 0],
            2: [1, 1],
            3: [1, 1],
            4: [1, 2],
            5: [1, 2],
            6: [1, 3],
            7: [1, 3],
            8: [0, 0],
            9: [0, 0],
            10: [0, 1],
            11: [0, 1],
            12: [0, 2],
            13: [0, 2],
            14: [0, 3],
            15: [0, 3],
            16: [2, 0],
            17: [2, 0],
            18: [2, 1],
            19: [2, 1],
            20: [2, 2],
            21: [2, 2],
            22: [2, 3],
            23: [2, 3],
            24: [3, 9],
            25: [0, 9],
            26: [1, 9],
            27: [2, 9],
            28: [4, 9],
            29: [0, 5],
            30: [1, 5],
            31: [2, 5],
            32: [0, 9],
            33: [1, 9],
            34: [2, 9],
            35: [1, 8],
            36: [0, 8],
            37: [1, 8],
            38: [1, 8],
            39: [1, 4],
            40: [0, 4],
            41: [2, 4],
            42: [0, 6],
            43: [1, 6],
            44: [0, 7],
            45: [1, 7],
            46: [1, 9],
            47: [0, 9],
            48: [1, 9],
            49: [0, 9]
        }

class_mapping = torch.Tensor(list(label_mapping.values()))
class_mapping = class_mapping.to(int)

cls1_map,cls2_map = torch.split(class_mapping,[1,1],1)
cls1_map = cls1_map.squeeze(1)
cls2_map = cls2_map.squeeze(1)
# print(cls1_map.dtype)
cls1 = torch.zeros((int(cls1_map.max())+1,len(cls1_map)))
cls1 = cls1.scatter(0,cls1_map.unsqueeze(0),1)


cls2 = torch.zeros((int(cls2_map.max())+1,len(cls2_map)))
cls2 = cls2.scatter(0,cls2_map.unsqueeze(0),1)
# cls2.shape

torch.Size([10, 50])

In [83]:
pred = torch.rand((1,23,20))
# cc = torch.rand((1,23,10))

predn = torch.matmul(pred[...,5:5+cls1.shape[0]],cls1) + \
torch.matmul(pred[...,5+cls1.shape[0]:5+cls1.shape[0]+cls2.shape[0]],cls2)
# dd = torch.matmul(gg[...,5+cls1.shape[0]:5+cls1.shape[0]+cls2.shape[0]],cls2)
# 5+cls1.shape[0]+cls2.shape[0]

In [48]:
cls1_map.squeeze().shape

torch.Size([50])

In [45]:
import torch

# 假设你有一个形状为 (50, 1) 的张量 a
a = torch.randn(50, 1)

# 使用 squeeze 函数去除大小为 1 的维度
a_flat = a.squeeze()

# 打印结果的形状
print("Original shape:", a.shape)  # 应该是 (50, 1)
print("New shape:", a_flat.shape)  # 应该是 (50,)


Original shape: torch.Size([50, 1])
New shape: torch.Size([50])


In [6]:
import os
label_path = "G:\TLD_train7\labels\train"
new_label_path = "f:/datasets/TSR_TFL/labels/test2_new"
if not os.path.exists(new_label_path):
    os.makedirs(new_label_path)

list_dir = os.listdir(label_path)
# list_dir
for file in list_dir:
    res = []
    with open(os.path.join(label_path, file), "r") as f:
        for line in f.readlines():
            c,x,y,w,h = line.split(" ")
            #这里写修改规则
            c = label_map[c]
            # if float(w)>0.08 or float(h)>0.09 and int(c) <= 28:
            #     c = str(int(c)+50)
            res.append(c+" "+x+" "+y+" "+w+" "+h)
    with open(os.path.join(new_label_path, file), "w") as f:
        f.write("".join(res))


In [28]:
a = [1, 4, 2, 5, 8, 5, 2, 1, 6, 3, 5, 7, 4, 0, 3, 9, 2, 8, 1, 5,
     7, 0, 4, 3, 6, 9, 1, 5, 7, 2, 8, 0, 6, 3, 4, 9, 2, 5, 7, 1,
     8, 0, 6, 3, 9, 4, 2, 5, 7, 1]
a_tensor = torch.tensor(a)
a_tensor.unsqueeze(0).shape

torch.Size([1, 50])

In [ ]:
values_tensor = torch.tensor(list(self.label_mapping.values()), device=self.device)

In [62]:
import torch

# 假设你有一个长度为50的列表a
a = [1, 4, 2, 5, 8, 5, 2, 1, 6, 3, 5, 7, 4, 0, 3, 9, 2, 8, 1, 5,
     7, 0, 4, 3, 6, 9, 1, 5, 7, 2, 8, 0, 6, 3, 4, 9, 2, 5, 7, 1,
     8, 0, 6, 3, 9, 4, 2, 5, 7, 1]

# 将列表转换为张量
a_tensor = torch.tensor(a)

# 创建一个全零的张量，形状为(10, 50)
b = torch.zeros(10, len(a))

# 使用scatter_函数更新张量b，将对应位置的元素设为1
b.scatter_(0, a_tensor.unsqueeze(0), 1)

# 打印结果
print(b.shape)


torch.Size([10, 50])


In [7]:
# /*temp 查看label*/
import os
label_path = r"G:\TLD_train7\labels\train"
# new_label_path = "f:/datasets/TSR_TFL/labels/test2_new"
# if not os.path.exists(new_label_path):
    # os.makedirs(new_label_path)

list_dir = os.listdir(label_path)
# list_dir
for file in list_dir:
    res = []
    with open(os.path.join(label_path, file), "r") as f:
        for line in f.readlines():
            c,x,y,w,h = line.split(" ")
            #这里写修改规则
            if int(c) > 49:
                print("超出49了",label_path,file)
            # c = label_map[c]
            # if float(w)>0.08 or float(h)>0.09 and int(c) <= 28:
            #     c = str(int(c)+50)
            res.append(c+" "+x+" "+y+" "+w+" "+h)
    # with open(os.path.join(new_label_path, file), "w") as f:
    #     f.write("".join(res))


超出49了 G:\TLD_train7\labels\train h5f_39_97454.txt


In [5]:
a = "14 0.664188 0.290529 0.025355 0.106994"
q,w,e,r,t = a.split(" ")
w

'0.664188'