In [ ]:
import numpy as np

ndarray存放同类型元素的数组  
ndarray在内存中都有相同存储大小的区域  
组成：
![](./img/27.png)
* 一个指向数据的指针
* 数据类型或dtype，描述在数组中的固定大小值得格子
* 一个表示数组形状(shape)的元组，表示各维度大小的元组
* 一个跨度元组(stride)

array函数
asarray函数，跟array基本一致
empty未初始化，值可能是随机的
zeros、ones
full(object, full_values = 222)
eye生成对角线为1，其余为0的矩阵
arange
frombuffer(x, dtype = "S1"),以流的形式读入
fromiter(x,dtype = "f")
linspace()

random
random.rand(3,2)
random.random(4) #生成4个0-1随机浮点数
random.randint(2,7,5) #生成5个2-7随机数
random.randn(2,4)#生成以0为均值，1为标准差的正态分布的2*4数组
random.normal(loc = 1, scale = 2, size = 5)#生成以1为均值，2为标准差的正态分布的5个数

In [40]:
print(np.random.randint(2,7,5))
print(np.random.randn(2,4))

[4 5 3 4 5]
[[ 1.35225526 -0.6116454  -0.23108503 -0.39452973]
 [ 1.60014278 -0.4635966  -2.01949381 -1.53948183]]


In [35]:
# 一维数组
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print('---------')
# 多维数组
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print('---------')
arr = np.array([1,2,3,4,5,6,7,8,9,0], ndmin = 2)# 限定最小维度
print(arr)
print('---------')
#结构化数据
student = np.dtype([("name","S20"),("age","i4"),("marks","f4")])
arr = np.array([("sss",18,94.5),("ggg",25,55)],dtype = student)
print(arr)
print('---------')
arr = np.empty([3,2],dtype = int)
print(arr)
print('---------')

[1 2 3 4 5]
<class 'numpy.ndarray'>
---------
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
---------
[[1 2 3 4 5 6 7 8 9 0]]
---------
[(b'sss', 18, 94.5) (b'ggg', 25, 55. )]
---------
[[1 2]
 [3 4]
 [5 6]]
---------


In [37]:
arr = np.zeros(10)
print(arr)
print('---------')
arr = np.zeros(10,dtype = int)
print(arr)
print('---------')
arr = np.ones(10)
print(arr)
print('---------')
arr = np.full(10,99)
print(arr)
print('---------')
arr = np.eye(4,dtype = "i2")
print(arr)
arr = np.arange(1,12,2)
print(arr)
print('---------')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
---------
[0 0 0 0 0 0 0 0 0 0]
---------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
---------
[99 99 99 99 99 99 99 99 99 99]
---------
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[ 1  3  5  7  9 11]
---------


In [32]:
arr = np.array("ffsfs")
print(arr)
arr = np.frombuffer(b"ffsff",dtype = "S1")
print(arr)

ffsfs
[b'f' b'f' b's' b'f' b'f']


In [46]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)
print(arr.shape)
print(arr.itemsize) # 元素所占字节数
print(arr.flags)


6
(2, 3)
4
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



  C_CONTIGUOUS : True 行项是否连续
  F_CONTIGUOUS : False 数据是否在单一风格的fortran风格的连续段中
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

## 切片 & 索引

In [49]:
arr = np.arange(10)
s = slice(3,9,2)
print(arr[s])
print(arr[3:9:2])

[3 5 7]
[3 5 7]


In [51]:
arr = np.arange(15)
arr.shape = (5, 3)
print(arr[..., 1])
print(arr[1:3, ...])

[ 1  4  7 10 13]
[[3 4 5]
 [6 7 8]]
