In [1]:
import numpy as np

## 切片 & 索引

In [2]:
arr = np.arange(10)
s = slice(3,9,2)
print(arr[s])
print(arr[3:9:2])

[3 5 7]
[3 5 7]


In [3]:
arr = np.arange(15)
arr.shape = (5, 3)
print(arr[..., 1])
print(arr[1:3, ...])

[ 1  4  7 10 13]
[[3 4 5]
 [6 7 8]]


## 索引

In [7]:
arr = np.arange(15)
arr = arr.reshape((5,3))
print(arr)
print("----------")
rows = np.array([[4,0],[3,3]])
cols = np.array([[0,2],[1,1]])
print(arr[rows,cols])
print("----------")

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
----------
[[12  2]
 [10 10]]


In [8]:
print(arr[arr>5])

[ 6  7  8  9 10 11 12 13 14]


In [29]:
arr = np.array([[5,2,3,5,6],[2,36,3,6,3],[0,1,0,0,1],[55,33,66,77,11],[9,8,7,6,5],[66,44,20,9,5]])

In [30]:
arr[arr[:,2]>(arr[:,3]+arr[:,4])]

array([[66, 44, 20,  9,  5]])

In [36]:
arr[...,0]

array([ 5,  2,  0, 55,  9, 66])

In [33]:
arr[arr[0]>(arr[1]+arr[2])]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 5