In [2]:
import numpy as np

## any函数
如果满足条件（为True）
## all函数
如果所有都满足条件(为True)

In [9]:
# 先随机生成一个数组
b = np.random.randint(1,10,[10,2])#从1-10随机，2行6列数组
b


array([[2, 6],
       [4, 5],
       [5, 2],
       [9, 2],
       [6, 9],
       [2, 6],
       [5, 2],
       [1, 8],
       [4, 5],
       [2, 8]])

In [10]:
print((b>8).any(0)) # 如果一列中存在大于8的数
print((b>8).any(1)) # 如果一行中存在大于8的数

[ True  True]
[False False False  True  True False False False False False]


In [11]:
c = b[(b>2).all(1)]
c

array([[4, 5],
       [6, 9],
       [4, 5]])

In [12]:
# 还有一种用法，使用np.any
np.all(b[:,:]>2, 0)

array([False, False])