In [1]:
import torch

In [3]:
x = torch.arange(4, device = "cpu", dtype = torch.float)
x

tensor([0., 1., 2., 3.])

In [19]:
x = torch.ones(1,45,80,80)
x.shape

torch.Size([1, 45, 80, 80])

In [20]:
y = torch.ones(1,45,40,40)
y = y+y
y.shape

torch.Size([1, 45, 40, 40])

In [29]:
z = torch.zeros(1,45,20,20)
z.reshape(1,45,400)
z.shape

torch.Size([1, 45, 20, 20])

In [41]:
res = torch.concat((x.reshape(1,45,6400),y.reshape(1,45,1600),z.reshape(1,45,400)),2)

bs, ac, oo = res.shape
oo

8400

In [43]:
x = torch.arange(45*80*80)
x = x.reshape(1,45,80,80)
x

tensor([[[[     0,      1,      2,  ...,     77,     78,     79],
          [    80,     81,     82,  ...,    157,    158,    159],
          [   160,    161,    162,  ...,    237,    238,    239],
          ...,
          [  6160,   6161,   6162,  ...,   6237,   6238,   6239],
          [  6240,   6241,   6242,  ...,   6317,   6318,   6319],
          [  6320,   6321,   6322,  ...,   6397,   6398,   6399]],

         [[  6400,   6401,   6402,  ...,   6477,   6478,   6479],
          [  6480,   6481,   6482,  ...,   6557,   6558,   6559],
          [  6560,   6561,   6562,  ...,   6637,   6638,   6639],
          ...,
          [ 12560,  12561,  12562,  ...,  12637,  12638,  12639],
          [ 12640,  12641,  12642,  ...,  12717,  12718,  12719],
          [ 12720,  12721,  12722,  ...,  12797,  12798,  12799]],

         [[ 12800,  12801,  12802,  ...,  12877,  12878,  12879],
          [ 12880,  12881,  12882,  ...,  12957,  12958,  12959],
          [ 12960,  12961,  12962,  ...,  

In [18]:
x.reshape(1,45,6400)

tensor([[[     0,      1,      2,  ...,   6397,   6398,   6399],
         [  6400,   6401,   6402,  ...,  12797,  12798,  12799],
         [ 12800,  12801,  12802,  ...,  19197,  19198,  19199],
         ...,
         [268800, 268801, 268802,  ..., 275197, 275198, 275199],
         [275200, 275201, 275202,  ..., 281597, 281598, 281599],
         [281600, 281601, 281602,  ..., 287997, 287998, 287999]]])

In [37]:
a = torch.ones([1,2,4])
b = torch.ones([1,2,2])
torch.cat([a,b],2)


tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])